/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID merl-HP-Z840)
#  Generated on:      Tue Dec 28 23:51:12 2021
#  Design:            user_proj_example
#  Command:           eval_legacy {savenetlist -excludeLeafCell -includePowerGround -flat -exportTopPGNets ram_power.v}
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 28 2021 12:46:52 PKT (Dec 28 2021 07:46:52 UTC)
// Verification Directory fv/user_proj_example 
module user_proj_example (
	wb_clk_i, 
	wb_rst_i, 
	wbs_stb_i, 
	wbs_cyc_i, 
	wbs_we_i, 
	wbs_sel_i, 
	wbs_dat_i, 
	wbs_adr_i, 
	wbs_ack_o, 
	wbs_dat_o, 
	la_data_in, 
	la_data_out, 
	la_oenb, 
	io_in, 
	io_out, 
	io_oeb, 
	analog_io, 
	user_clock2, 
	user_irq, 
	VPWR, 
	VGND);
   input wb_clk_i;
   input wb_rst_i;
   input wbs_stb_i;
   input wbs_cyc_i;
   input wbs_we_i;
   input [3:0] wbs_sel_i;
   input [31:0] wbs_dat_i;
   input [31:0] wbs_adr_i;
   output wbs_ack_o;
   output [31:0] wbs_dat_o;
   input [127:0] la_data_in;
   output [127:0] la_data_out;
   input [127:0] la_oenb;
   input [37:0] io_in;
   output [37:0] io_out;
   output [37:0] io_oeb;
   inout [28:0] analog_io;
   input user_clock2;
   output [2:0] user_irq;
   inout VPWR;
   inout VGND;

   // Internal wires
   wire [31:0] \ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] ;
   wire [31:0] \ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata_1[0] ;
   wire [31:0] \ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] ;
   wire [31:0] \ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata_1[0] ;
   wire [31:0] dout1;
   wire [63:0] dout0;
   wire [15:0] addr;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED25;
   wire UNCONNECTED26;
   wire UNCONNECTED27;
   wire UNCONNECTED28;
   wire UNCONNECTED29;
   wire UNCONNECTED30;
   wire clk;
   wire csb0;
   wire csb1;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_16;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_24;
   wire n_232;
   wire n_233;
   wire n_283;
   wire n_284;
   wire n_294;
   wire n_300;
   wire n_306;
   wire n_312;
   wire n_318;
   wire n_324;
   wire n_330;
   wire n_336;
   wire n_340;
   wire n_341;
   wire n_492;
   wire n_496;
   wire n_500;
   wire n_504;
   wire n_508;
   wire n_512;
   wire n_516;
   wire n_520;
   wire n_521;
   wire n_524;
   wire n_527;
   wire n_530;
   wire n_533;
   wire n_536;
   wire n_539;
   wire n_542;
   wire n_548;
   wire n_556;
   wire n_564;
   wire n_572;
   wire n_580;
   wire n_588;
   wire n_596;
   wire n_604;
   wire n_612;
   wire n_620;
   wire n_628;
   wire n_636;
   wire n_644;
   wire n_652;
   wire n_660;
   wire n_668;
   wire n_673;
   wire n_676;
   wire n_679;
   wire n_682;
   wire n_685;
   wire n_688;
   wire n_691;
   wire n_694;
   wire n_697;
   wire n_700;
   wire n_703;
   wire n_706;
   wire n_709;
   wire n_712;
   wire n_715;
   wire n_718;
   wire n_748;
   wire n_752;
   wire n_756;
   wire n_760;
   wire n_764;
   wire n_768;
   wire n_772;
   wire n_776;
   wire n_780;
   wire n_784;
   wire n_788;
   wire n_792;
   wire n_796;
   wire n_800;
   wire n_804;
   wire n_808;
   wire n_812;
   wire n_816;
   wire n_820;
   wire n_824;
   wire n_828;
   wire n_832;
   wire n_836;
   wire n_840;
   wire n_844;
   wire n_848;
   wire n_852;
   wire n_856;
   wire n_860;
   wire n_864;
   wire n_868;
   wire n_872;
   wire n_876;
   wire n_880;
   wire n_884;
   wire n_888;
   wire n_892;
   wire n_896;
   wire n_900;
   wire n_904;
   wire \ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ;
   wire web;

   assign wbs_ack_o = io_oeb[27];
   assign wbs_dat_o[31] = io_oeb[27];
   assign wbs_dat_o[30] = io_oeb[27];
   assign wbs_dat_o[29] = io_oeb[27];
   assign wbs_dat_o[28] = io_oeb[27];
   assign wbs_dat_o[27] = io_oeb[27];
   assign wbs_dat_o[26] = io_oeb[27];
   assign wbs_dat_o[25] = io_oeb[27];
   assign wbs_dat_o[24] = io_oeb[27];
   assign wbs_dat_o[23] = io_oeb[27];
   assign wbs_dat_o[22] = io_oeb[27];
   assign wbs_dat_o[21] = io_oeb[27];
   assign wbs_dat_o[20] = io_oeb[27];
   assign wbs_dat_o[19] = io_oeb[27];
   assign wbs_dat_o[18] = io_oeb[27];
   assign wbs_dat_o[17] = io_oeb[27];
   assign wbs_dat_o[16] = io_oeb[27];
   assign wbs_dat_o[15] = io_oeb[27];
   assign wbs_dat_o[14] = io_oeb[27];
   assign wbs_dat_o[13] = io_oeb[27];
   assign wbs_dat_o[12] = io_oeb[27];
   assign wbs_dat_o[11] = io_oeb[27];
   assign wbs_dat_o[10] = io_oeb[27];
   assign wbs_dat_o[9] = io_oeb[27];
   assign wbs_dat_o[8] = io_oeb[27];
   assign wbs_dat_o[7] = io_oeb[27];
   assign wbs_dat_o[6] = io_oeb[27];
   assign wbs_dat_o[5] = io_oeb[27];
   assign wbs_dat_o[4] = io_oeb[27];
   assign wbs_dat_o[3] = io_oeb[27];
   assign wbs_dat_o[2] = io_oeb[27];
   assign wbs_dat_o[1] = io_oeb[27];
   assign wbs_dat_o[0] = io_oeb[27];
   assign la_data_out[127] = io_oeb[27];
   assign la_data_out[126] = io_oeb[27];
   assign la_data_out[125] = io_oeb[27];
   assign la_data_out[124] = io_oeb[27];
   assign la_data_out[123] = io_oeb[27];
   assign la_data_out[122] = io_oeb[27];
   assign la_data_out[121] = io_oeb[27];
   assign la_data_out[120] = io_oeb[27];
   assign la_data_out[65] = io_oeb[27];
   assign la_data_out[64] = io_oeb[27];
   assign la_data_out[63] = io_oeb[27];
   assign la_data_out[62] = io_oeb[27];
   assign la_data_out[51] = io_oeb[27];
   assign la_data_out[50] = io_oeb[27];
   assign la_data_out[49] = io_oeb[27];
   assign la_data_out[48] = io_oeb[27];
   assign la_data_out[47] = io_oeb[27];
   assign la_data_out[46] = io_oeb[27];
   assign la_data_out[45] = io_oeb[27];
   assign la_data_out[44] = io_oeb[27];
   assign la_data_out[43] = io_oeb[27];
   assign la_data_out[42] = io_oeb[27];
   assign la_data_out[41] = io_oeb[27];
   assign la_data_out[40] = io_oeb[27];
   assign la_data_out[39] = io_oeb[27];
   assign la_data_out[38] = io_oeb[27];
   assign la_data_out[37] = io_oeb[27];
   assign la_data_out[36] = io_oeb[27];
   assign la_data_out[35] = io_oeb[27];
   assign la_data_out[34] = io_oeb[27];
   assign la_data_out[33] = io_oeb[27];
   assign la_data_out[32] = io_oeb[27];
   assign la_data_out[31] = io_oeb[27];
   assign la_data_out[30] = io_oeb[27];
   assign la_data_out[29] = io_oeb[27];
   assign la_data_out[28] = io_oeb[27];
   assign la_data_out[27] = io_oeb[27];
   assign la_data_out[26] = io_oeb[27];
   assign la_data_out[25] = io_oeb[27];
   assign la_data_out[24] = io_oeb[27];
   assign la_data_out[23] = io_oeb[27];
   assign la_data_out[22] = io_oeb[27];
   assign la_data_out[21] = io_oeb[27];
   assign la_data_out[20] = io_oeb[27];
   assign la_data_out[19] = io_oeb[27];
   assign la_data_out[18] = io_oeb[27];
   assign la_data_out[17] = io_oeb[27];
   assign la_data_out[16] = io_oeb[27];
   assign la_data_out[15] = io_oeb[27];
   assign la_data_out[14] = io_oeb[27];
   assign la_data_out[13] = io_oeb[27];
   assign la_data_out[12] = io_oeb[27];
   assign la_data_out[11] = io_oeb[27];
   assign la_data_out[10] = io_oeb[27];
   assign la_data_out[9] = io_oeb[27];
   assign la_data_out[8] = io_oeb[27];
   assign la_data_out[7] = io_oeb[27];
   assign la_data_out[6] = io_oeb[27];
   assign la_data_out[5] = io_oeb[27];
   assign la_data_out[4] = io_oeb[27];
   assign la_data_out[3] = io_oeb[27];
   assign la_data_out[2] = io_oeb[27];
   assign la_data_out[1] = io_oeb[27];
   assign la_data_out[0] = io_oeb[27];
   assign io_out[37] = io_oeb[27];
   assign io_out[36] = io_oeb[27];
   assign io_out[35] = io_oeb[27];
   assign io_out[26] = io_oeb[27];
   assign io_out[25] = io_oeb[27];
   assign io_out[24] = io_oeb[27];
   assign io_out[23] = io_oeb[27];
   assign io_out[22] = io_oeb[27];
   assign io_out[21] = io_oeb[27];
   assign io_out[20] = io_oeb[27];
   assign io_out[19] = io_oeb[27];
   assign io_out[18] = io_oeb[27];
   assign io_out[17] = io_oeb[27];
   assign io_out[16] = io_oeb[27];
   assign io_out[15] = io_oeb[27];
   assign io_out[14] = io_oeb[27];
   assign io_out[13] = io_oeb[27];
   assign io_out[12] = io_oeb[27];
   assign io_out[11] = io_oeb[27];
   assign io_out[10] = io_oeb[27];
   assign io_out[9] = io_oeb[27];
   assign io_out[8] = io_oeb[27];
   assign io_out[7] = io_oeb[27];
   assign io_out[6] = io_oeb[27];
   assign io_out[5] = io_oeb[27];
   assign io_out[4] = io_oeb[27];
   assign io_out[3] = io_oeb[27];
   assign io_out[2] = io_oeb[27];
   assign io_out[1] = io_oeb[27];
   assign io_out[0] = io_oeb[27];
   assign io_oeb[37] = io_oeb[27];
   assign io_oeb[36] = io_oeb[27];
   assign io_oeb[35] = io_oeb[0];
   assign io_oeb[34] = io_oeb[27];
   assign io_oeb[33] = io_oeb[27];
   assign io_oeb[32] = io_oeb[27];
   assign io_oeb[31] = io_oeb[27];
   assign io_oeb[30] = io_oeb[27];
   assign io_oeb[29] = io_oeb[27];
   assign io_oeb[28] = io_oeb[27];
   assign io_oeb[26] = io_oeb[0];
   assign io_oeb[25] = io_oeb[0];
   assign io_oeb[24] = io_oeb[0];
   assign io_oeb[23] = io_oeb[0];
   assign io_oeb[22] = io_oeb[0];
   assign io_oeb[21] = io_oeb[0];
   assign io_oeb[20] = io_oeb[0];
   assign io_oeb[19] = io_oeb[0];
   assign io_oeb[18] = io_oeb[0];
   assign io_oeb[17] = io_oeb[0];
   assign io_oeb[16] = io_oeb[0];
   assign io_oeb[15] = io_oeb[0];
   assign io_oeb[14] = io_oeb[0];
   assign io_oeb[13] = io_oeb[0];
   assign io_oeb[12] = io_oeb[0];
   assign io_oeb[11] = io_oeb[0];
   assign io_oeb[10] = io_oeb[0];
   assign io_oeb[9] = io_oeb[0];
   assign io_oeb[8] = io_oeb[0];
   assign io_oeb[7] = io_oeb[27];
   assign io_oeb[6] = io_oeb[27];
   assign io_oeb[5] = io_oeb[0];
   assign io_oeb[4] = io_oeb[27];
   assign io_oeb[3] = io_oeb[0];
   assign io_oeb[2] = io_oeb[0];
   assign io_oeb[1] = io_oeb[0];
   assign user_irq[2] = io_oeb[27];
   assign user_irq[1] = io_oeb[27];
   assign user_irq[0] = io_oeb[27];

   // Module instantiations
   sky130_sram_1kbyte_1rw1r_32x256_8 \ram_2r1w_256x32_genblk1[0].ram_1rw_genblk1[0].genblk1.ram_i  (
	.din0({ la_data_in[50],
		la_data_in[49],
		la_data_in[48],
		la_data_in[47],
		la_data_in[46],
		la_data_in[45],
		la_data_in[44],
		la_data_in[43],
		la_data_in[42],
		la_data_in[41],
		la_data_in[40],
		la_data_in[39],
		la_data_in[38],
		la_data_in[37],
		la_data_in[36],
		la_data_in[35],
		la_data_in[34],
		la_data_in[33],
		la_data_in[32],
		la_data_in[31],
		la_data_in[30],
		la_data_in[29],
		la_data_in[28],
		la_data_in[27],
		la_data_in[26],
		la_data_in[25],
		la_data_in[24],
		la_data_in[23],
		la_data_in[22],
		la_data_in[21],
		la_data_in[20],
		la_data_in[19] }),
	.dout0(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] ),
	.addr0({ n_792,
		n_760,
		n_776,
		n_784,
		n_764,
		n_756,
		n_772,
		n_796 }),
	.wmask0({ io_oeb[0],
		io_oeb[0],
		io_oeb[0],
		io_oeb[0] }),
	.csb0(n_283),
	.web0(web),
	.clk0(clk),
	.dout1(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata_1[0] ),
	.addr1({ n_872,
		n_868,
		n_820,
		n_848,
		n_836,
		n_832,
		n_860,
		n_864 }),
	.csb1(io_oeb[0]),
	.clk1(clk), 
	.vssd1(VGND), 
	.vccd1(VPWR));
   sky130_sram_1kbyte_1rw1r_32x256_8 \ram_2r1w_256x32_genblk1[1].ram_1rw_genblk1[0].genblk1.ram_i  (
	.din0({ la_data_in[50],
		la_data_in[49],
		la_data_in[48],
		la_data_in[47],
		la_data_in[46],
		la_data_in[45],
		la_data_in[44],
		la_data_in[43],
		la_data_in[42],
		la_data_in[41],
		la_data_in[40],
		la_data_in[39],
		la_data_in[38],
		la_data_in[37],
		la_data_in[36],
		la_data_in[35],
		la_data_in[34],
		la_data_in[33],
		la_data_in[32],
		la_data_in[31],
		la_data_in[30],
		la_data_in[29],
		la_data_in[28],
		la_data_in[27],
		la_data_in[26],
		la_data_in[25],
		la_data_in[24],
		la_data_in[23],
		la_data_in[22],
		la_data_in[21],
		la_data_in[20],
		la_data_in[19] }),
	.dout0(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] ),
	.addr0({ n_748,
		n_880,
		n_896,
		n_892,
		n_900,
		n_884,
		n_904,
		n_888 }),
	.wmask0({ io_oeb[0],
		io_oeb[0],
		io_oeb[0],
		io_oeb[0] }),
	.csb0(csb0),
	.web0(n_340),
	.clk0(clk),
	.dout1(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata_1[0] ),
	.addr1({ n_500,
		n_516,
		n_492,
		n_508,
		n_512,
		n_520,
		n_504,
		n_496 }),
	.csb1(io_oeb[0]),
	.clk1(clk), 
	.vssd1(VGND), 
	.vccd1(VPWR));
   sky130_sram_1kbyte_1rw1r_32x256_8 sram (
	.din0({ la_data_in[50],
		la_data_in[49],
		la_data_in[48],
		la_data_in[47],
		la_data_in[46],
		la_data_in[45],
		la_data_in[44],
		la_data_in[43],
		la_data_in[42],
		la_data_in[41],
		la_data_in[40],
		la_data_in[39],
		la_data_in[38],
		la_data_in[37],
		la_data_in[36],
		la_data_in[35],
		la_data_in[34],
		la_data_in[33],
		la_data_in[32],
		la_data_in[31],
		la_data_in[30],
		la_data_in[29],
		la_data_in[28],
		la_data_in[27],
		la_data_in[26],
		la_data_in[25],
		la_data_in[24],
		la_data_in[23],
		la_data_in[22],
		la_data_in[21],
		la_data_in[20],
		la_data_in[19] }),
	.dout0(dout1),
	.addr0({ n_824,
		n_816,
		n_828,
		n_856,
		n_852,
		n_844,
		n_840,
		n_876 }),
	.wmask0({ io_oeb[0],
		io_oeb[0],
		io_oeb[0],
		io_oeb[0] }),
	.csb0(csb1),
	.web0(web),
	.clk0(clk),
	.dout1({ UNCONNECTED,
		UNCONNECTED0,
		UNCONNECTED1,
		UNCONNECTED2,
		UNCONNECTED3,
		UNCONNECTED4,
		UNCONNECTED5,
		UNCONNECTED6,
		UNCONNECTED7,
		UNCONNECTED8,
		UNCONNECTED9,
		UNCONNECTED10,
		UNCONNECTED11,
		UNCONNECTED12,
		UNCONNECTED13,
		UNCONNECTED14,
		UNCONNECTED15,
		UNCONNECTED16,
		UNCONNECTED17,
		UNCONNECTED18,
		UNCONNECTED19,
		UNCONNECTED20,
		UNCONNECTED21,
		UNCONNECTED22,
		UNCONNECTED23,
		UNCONNECTED24,
		UNCONNECTED25,
		UNCONNECTED26,
		UNCONNECTED27,
		UNCONNECTED28,
		UNCONNECTED29,
		UNCONNECTED30 }),
	.addr1({ n_808,
		n_752,
		n_812,
		n_788,
		n_768,
		n_780,
		n_804,
		n_800 }),
	.csb1(io_oeb[0]),
	.clk1(clk), 
	.vssd1(VGND), 
	.vccd1(VPWR));
   sky130_fd_sc_hd__mux2_2 g1784__2398 (
	.A0(la_data_in[65]),
	.A1(wb_clk_i),
	.S(la_oenb[65]),
	.X(clk), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfrtn_1 csb0_reg (
	.CLK_N(clk),
	.D(la_data_in[0]),
	.Q(csb0),
	.RESET_B(io_oeb[0]),
	.SCD(io_in[8]),
	.SCE(la_oenb[0]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfrtn_1 csb1_reg (
	.CLK_N(clk),
	.D(la_data_in[1]),
	.Q(csb1),
	.RESET_B(io_oeb[0]),
	.SCD(io_in[9]),
	.SCE(la_oenb[1]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__dfstp_4 \ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg_reg  (
	.CLK(clk),
	.D(n_340),
	.Q(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ),
	.SET_B(io_oeb[0]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfrtn_1 web_reg (
	.CLK_N(clk),
	.D(la_data_in[2]),
	.Q(web),
	.RESET_B(io_oeb[0]),
	.SCD(io_in[10]),
	.SCE(la_oenb[2]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2_1 g3035__5107 (
	.A(n_16),
	.B(n_24),
	.Y(la_data_out[69]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2_1 g3036__6260 (
	.A(n_18),
	.B(n_24),
	.Y(la_data_out[68]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2_1 g3037__4319 (
	.A(n_12),
	.B(n_24),
	.Y(la_data_out[67]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2_1 g3038__8428 (
	.A(n_14),
	.B(n_24),
	.Y(la_data_out[66]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3043__5526 (
	.A1(n_21),
	.A2(dout1[28]),
	.B1(dout0[28]),
	.B2(n_20),
	.X(la_data_out[94]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3044__6783 (
	.A1(n_21),
	.A2(dout1[27]),
	.B1(dout0[27]),
	.B2(n_20),
	.X(la_data_out[93]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3045__3680 (
	.A1(n_21),
	.A2(dout1[15]),
	.B1(dout0[15]),
	.B2(n_20),
	.X(la_data_out[81]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3046__1617 (
	.A1(n_21),
	.A2(dout1[16]),
	.B1(dout0[16]),
	.B2(n_20),
	.X(la_data_out[82]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3047__2802 (
	.A1(n_21),
	.A2(dout1[14]),
	.B1(dout0[14]),
	.B2(n_20),
	.X(la_data_out[80]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3048__1705 (
	.A1(n_21),
	.A2(dout1[13]),
	.B1(dout0[13]),
	.B2(n_20),
	.X(la_data_out[79]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3049__5122 (
	.A1(n_21),
	.A2(dout1[26]),
	.B1(dout0[26]),
	.B2(n_20),
	.X(la_data_out[92]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3050__8246 (
	.A1(n_21),
	.A2(dout1[12]),
	.B1(dout0[12]),
	.B2(n_20),
	.X(la_data_out[78]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3051__7098 (
	.A1(n_21),
	.A2(dout1[11]),
	.B1(dout0[11]),
	.B2(n_20),
	.X(la_data_out[77]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3052__6131 (
	.A1(n_21),
	.A2(dout1[10]),
	.B1(dout0[10]),
	.B2(n_20),
	.X(la_data_out[76]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3053__1881 (
	.A1(n_21),
	.A2(dout1[25]),
	.B1(dout0[25]),
	.B2(n_20),
	.X(la_data_out[91]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3054__5115 (
	.A1(n_21),
	.A2(dout1[9]),
	.B1(dout0[9]),
	.B2(n_20),
	.X(la_data_out[75]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3055__7482 (
	.A1(n_21),
	.A2(dout1[8]),
	.B1(dout0[8]),
	.B2(n_20),
	.X(la_data_out[74]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3056__4733 (
	.A1(n_21),
	.A2(dout1[7]),
	.B1(dout0[7]),
	.B2(n_20),
	.X(la_data_out[73]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3057__6161 (
	.A1(n_21),
	.A2(dout1[24]),
	.B1(dout0[24]),
	.B2(n_20),
	.X(la_data_out[90]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3058__9315 (
	.A1(n_21),
	.A2(dout1[6]),
	.B1(dout0[6]),
	.B2(n_20),
	.X(la_data_out[72]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3059__9945 (
	.A1(n_21),
	.A2(dout1[5]),
	.B1(dout0[5]),
	.B2(n_20),
	.X(la_data_out[71]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3060__2883 (
	.A1(n_21),
	.A2(dout1[23]),
	.B1(dout0[23]),
	.B2(n_20),
	.X(la_data_out[89]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3061__2346 (
	.A1(n_21),
	.A2(dout1[4]),
	.B1(dout0[4]),
	.B2(n_20),
	.X(la_data_out[70]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3062__1666 (
	.A1(n_21),
	.A2(dout1[30]),
	.B1(dout0[30]),
	.B2(n_20),
	.X(la_data_out[96]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3063__7410 (
	.A1(n_21),
	.A2(dout1[21]),
	.B1(dout0[21]),
	.B2(n_20),
	.X(la_data_out[87]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3064__6417 (
	.A1(n_21),
	.A2(dout1[22]),
	.B1(dout0[22]),
	.B2(n_20),
	.X(la_data_out[88]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3065__5477 (
	.A1(n_21),
	.A2(dout1[31]),
	.B1(dout0[31]),
	.B2(n_20),
	.X(la_data_out[97]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3066__2398 (
	.A1(n_21),
	.A2(dout1[20]),
	.B1(dout0[20]),
	.B2(n_20),
	.X(la_data_out[86]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3067__5107 (
	.A1(n_21),
	.A2(dout1[19]),
	.B1(dout0[19]),
	.B2(n_20),
	.X(la_data_out[85]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3068__6260 (
	.A1(n_21),
	.A2(dout1[18]),
	.B1(dout0[18]),
	.B2(n_20),
	.X(la_data_out[84]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3069__4319 (
	.A1(n_21),
	.A2(dout1[29]),
	.B1(dout0[29]),
	.B2(n_20),
	.X(la_data_out[95]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3070__8428 (
	.A1(n_232),
	.A2(dout1[7]),
	.B1(dout0[35]),
	.B2(n_22),
	.X(io_out[34]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3071__5526 (
	.A1(n_232),
	.A2(dout1[6]),
	.B1(dout0[34]),
	.B2(n_22),
	.X(io_out[33]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3072__6783 (
	.A1(n_21),
	.A2(dout1[17]),
	.B1(dout0[17]),
	.B2(n_20),
	.X(la_data_out[83]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3073__3680 (
	.A1(n_232),
	.A2(dout1[5]),
	.B1(dout0[33]),
	.B2(n_22),
	.X(io_out[32]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a22o_1 g3074__1617 (
	.A1(n_232),
	.A2(dout1[4]),
	.B1(dout0[32]),
	.B2(n_22),
	.X(io_out[31]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3075__2802 (
	.A(dout0[43]),
	.B(n_20),
	.X(la_data_out[99]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3076__1705 (
	.A(dout0[33]),
	.B(n_20),
	.X(la_data_out[53]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3077__5122 (
	.A(dout0[58]),
	.B(n_20),
	.X(la_data_out[114]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3078__8246 (
	.A(dout0[50]),
	.B(n_20),
	.X(la_data_out[106]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3079__7098 (
	.A(dout0[49]),
	.B(n_20),
	.X(la_data_out[105]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3080__6131 (
	.A(dout0[48]),
	.B(n_20),
	.X(la_data_out[104]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3081__1881 (
	.A(dout0[57]),
	.B(n_20),
	.X(la_data_out[113]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3082__5115 (
	.A(dout0[62]),
	.B(n_20),
	.X(la_data_out[118]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3083__7482 (
	.A(dout0[47]),
	.B(n_20),
	.X(la_data_out[103]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3084__4733 (
	.A(dout0[61]),
	.B(n_20),
	.X(la_data_out[117]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3085__6161 (
	.A(dout0[56]),
	.B(n_20),
	.X(la_data_out[112]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3086__9315 (
	.A(dout0[46]),
	.B(n_20),
	.X(la_data_out[102]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3087__9945 (
	.A(dout0[45]),
	.B(n_20),
	.X(la_data_out[101]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3088__2883 (
	.A(dout0[55]),
	.B(n_20),
	.X(la_data_out[111]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3089__2346 (
	.A(dout0[44]),
	.B(n_20),
	.X(la_data_out[100]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3090__1666 (
	.A(dout0[32]),
	.B(n_20),
	.X(la_data_out[52]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3091__7410 (
	.A(dout0[54]),
	.B(n_20),
	.X(la_data_out[110]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3092__6417 (
	.A(dout0[51]),
	.B(n_20),
	.X(la_data_out[107]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3093__5477 (
	.A(dout0[60]),
	.B(n_20),
	.X(la_data_out[116]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3094__2398 (
	.A(dout0[42]),
	.B(n_20),
	.X(la_data_out[98]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3095__5107 (
	.A(dout0[53]),
	.B(n_20),
	.X(la_data_out[109]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3096__6260 (
	.A(dout0[41]),
	.B(n_20),
	.X(la_data_out[61]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3097__4319 (
	.A(dout0[40]),
	.B(n_20),
	.X(la_data_out[60]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3098__8428 (
	.A(dout0[59]),
	.B(n_20),
	.X(la_data_out[115]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3099__5526 (
	.A(dout0[39]),
	.B(n_20),
	.X(la_data_out[59]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3100__6783 (
	.A(dout0[38]),
	.B(n_20),
	.X(la_data_out[58]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3101__3680 (
	.A(dout0[37]),
	.B(n_20),
	.X(la_data_out[57]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3102__1617 (
	.A(dout0[36]),
	.B(n_20),
	.X(la_data_out[56]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3103__2802 (
	.A(dout0[35]),
	.B(n_20),
	.X(la_data_out[55]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3104__1705 (
	.A(dout0[34]),
	.B(n_20),
	.X(la_data_out[54]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3105__5122 (
	.A(dout0[52]),
	.B(n_20),
	.X(la_data_out[108]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_1 g3106__8246 (
	.A(dout0[63]),
	.B(n_20),
	.X(la_data_out[119]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nand2b_1 g3107__7098 (
	.A_N(io_in[35]),
	.B(n_11),
	.Y(n_24), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2_1 g3109__6131 (
	.A(n_9),
	.B(csb0),
	.Y(n_22), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2_2 g3110__1881 (
	.A(n_233),
	.B(n_10),
	.X(n_21), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and2b_4 g3111__5115 (
	.A_N(csb0),
	.B(n_10),
	.X(n_20), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2i_1 g3116__7482 (
	.A0(dout0[2]),
	.A1(dout1[2]),
	.S(csb0),
	.Y(n_18), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2i_1 g3117__4733 (
	.A0(dout0[3]),
	.A1(dout1[3]),
	.S(n_283),
	.Y(n_16), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2i_1 g3118__6161 (
	.A0(dout0[0]),
	.A1(dout1[0]),
	.S(csb0),
	.Y(n_14), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2i_1 g3119__9315 (
	.A0(dout0[1]),
	.A1(dout1[1]),
	.S(n_283),
	.Y(n_12), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__a21boi_1 g3120__9945 (
	.A1(n_283),
	.A2(csb1),
	.B1_N(n_340),
	.Y(n_11), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2b_1 g3122__2883 (
	.A(io_in[35]),
	.B_N(n_340),
	.Y(n_10), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nand2_1 g3124__2346 (
	.A(io_in[35]),
	.B(n_340),
	.Y(n_9), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[0]  (
	.CLK(clk),
	.D(dout0[0]),
	.Q(dout0[0]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [0]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[1]  (
	.CLK(clk),
	.D(dout0[1]),
	.Q(dout0[1]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [1]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[2]  (
	.CLK(clk),
	.D(dout0[2]),
	.Q(dout0[2]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [2]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[3]  (
	.CLK(clk),
	.D(dout0[3]),
	.Q(dout0[3]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [3]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[4]  (
	.CLK(clk),
	.D(dout0[4]),
	.Q(dout0[4]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [4]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[5]  (
	.CLK(clk),
	.D(dout0[5]),
	.Q(dout0[5]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [5]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[6]  (
	.CLK(clk),
	.D(dout0[6]),
	.Q(dout0[6]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [6]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[7]  (
	.CLK(clk),
	.D(dout0[7]),
	.Q(dout0[7]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [7]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[8]  (
	.CLK(clk),
	.D(dout0[8]),
	.Q(dout0[8]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [8]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[9]  (
	.CLK(clk),
	.D(dout0[9]),
	.Q(dout0[9]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [9]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[10]  (
	.CLK(clk),
	.D(dout0[10]),
	.Q(dout0[10]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [10]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[11]  (
	.CLK(clk),
	.D(dout0[11]),
	.Q(dout0[11]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [11]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[12]  (
	.CLK(clk),
	.D(dout0[12]),
	.Q(dout0[12]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [12]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[13]  (
	.CLK(clk),
	.D(dout0[13]),
	.Q(dout0[13]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [13]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[14]  (
	.CLK(clk),
	.D(dout0[14]),
	.Q(dout0[14]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [14]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[15]  (
	.CLK(clk),
	.D(dout0[15]),
	.Q(dout0[15]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [15]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[16]  (
	.CLK(clk),
	.D(dout0[16]),
	.Q(dout0[16]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [16]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[17]  (
	.CLK(clk),
	.D(dout0[17]),
	.Q(dout0[17]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [17]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[18]  (
	.CLK(clk),
	.D(dout0[18]),
	.Q(dout0[18]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [18]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[19]  (
	.CLK(clk),
	.D(dout0[19]),
	.Q(dout0[19]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [19]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[20]  (
	.CLK(clk),
	.D(dout0[20]),
	.Q(dout0[20]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [20]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[21]  (
	.CLK(clk),
	.D(dout0[21]),
	.Q(dout0[21]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [21]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[22]  (
	.CLK(clk),
	.D(dout0[22]),
	.Q(dout0[22]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [22]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[23]  (
	.CLK(clk),
	.D(dout0[23]),
	.Q(dout0[23]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [23]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[24]  (
	.CLK(clk),
	.D(dout0[24]),
	.Q(dout0[24]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [24]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[25]  (
	.CLK(clk),
	.D(dout0[25]),
	.Q(dout0[25]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [25]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[26]  (
	.CLK(clk),
	.D(dout0[26]),
	.Q(dout0[26]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [26]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[27]  (
	.CLK(clk),
	.D(dout0[27]),
	.Q(dout0[27]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [27]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[28]  (
	.CLK(clk),
	.D(dout0[28]),
	.Q(dout0[28]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [28]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[29]  (
	.CLK(clk),
	.D(dout0[29]),
	.Q(dout0[29]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [29]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[30]  (
	.CLK(clk),
	.D(dout0[30]),
	.Q(dout0[30]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [30]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[0].ram_1rw_RData_out_reg[31]  (
	.CLK(clk),
	.D(dout0[31]),
	.Q(dout0[31]),
	.SCD(\ram_2r1w_256x32_genblk1[0].ram_1rw_Rdata[0] [31]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[0]  (
	.CLK(clk),
	.D(dout0[32]),
	.Q(dout0[32]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [0]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[1]  (
	.CLK(clk),
	.D(dout0[33]),
	.Q(dout0[33]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [1]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[2]  (
	.CLK(clk),
	.D(dout0[34]),
	.Q(dout0[34]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [2]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[3]  (
	.CLK(clk),
	.D(dout0[35]),
	.Q(dout0[35]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [3]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[4]  (
	.CLK(clk),
	.D(dout0[36]),
	.Q(dout0[36]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [4]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[5]  (
	.CLK(clk),
	.D(dout0[37]),
	.Q(dout0[37]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [5]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[6]  (
	.CLK(clk),
	.D(dout0[38]),
	.Q(dout0[38]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [6]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[7]  (
	.CLK(clk),
	.D(dout0[39]),
	.Q(dout0[39]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [7]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[8]  (
	.CLK(clk),
	.D(dout0[40]),
	.Q(dout0[40]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [8]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[9]  (
	.CLK(clk),
	.D(dout0[41]),
	.Q(dout0[41]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [9]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[10]  (
	.CLK(clk),
	.D(dout0[42]),
	.Q(dout0[42]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [10]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[11]  (
	.CLK(clk),
	.D(dout0[43]),
	.Q(dout0[43]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [11]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[12]  (
	.CLK(clk),
	.D(dout0[44]),
	.Q(dout0[44]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [12]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[13]  (
	.CLK(clk),
	.D(dout0[45]),
	.Q(dout0[45]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [13]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[14]  (
	.CLK(clk),
	.D(dout0[46]),
	.Q(dout0[46]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [14]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[15]  (
	.CLK(clk),
	.D(dout0[47]),
	.Q(dout0[47]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [15]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[16]  (
	.CLK(clk),
	.D(dout0[48]),
	.Q(dout0[48]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [16]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[17]  (
	.CLK(clk),
	.D(dout0[49]),
	.Q(dout0[49]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [17]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[18]  (
	.CLK(clk),
	.D(dout0[50]),
	.Q(dout0[50]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [18]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[19]  (
	.CLK(clk),
	.D(dout0[51]),
	.Q(dout0[51]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [19]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[20]  (
	.CLK(clk),
	.D(dout0[52]),
	.Q(dout0[52]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [20]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[21]  (
	.CLK(clk),
	.D(dout0[53]),
	.Q(dout0[53]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [21]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[22]  (
	.CLK(clk),
	.D(dout0[54]),
	.Q(dout0[54]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [22]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[23]  (
	.CLK(clk),
	.D(dout0[55]),
	.Q(dout0[55]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [23]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[24]  (
	.CLK(clk),
	.D(dout0[56]),
	.Q(dout0[56]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [24]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[25]  (
	.CLK(clk),
	.D(dout0[57]),
	.Q(dout0[57]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [25]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[26]  (
	.CLK(clk),
	.D(dout0[58]),
	.Q(dout0[58]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [26]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[27]  (
	.CLK(clk),
	.D(dout0[59]),
	.Q(dout0[59]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [27]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[28]  (
	.CLK(clk),
	.D(dout0[60]),
	.Q(dout0[60]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [28]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[29]  (
	.CLK(clk),
	.D(dout0[61]),
	.Q(dout0[61]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [29]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[30]  (
	.CLK(clk),
	.D(dout0[62]),
	.Q(dout0[62]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [30]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__sdfxtp_1 \ram_2r1w_256x32_genblk1[1].ram_1rw_RData_out_reg[31]  (
	.CLK(clk),
	.D(dout0[63]),
	.Q(dout0[63]),
	.SCD(\ram_2r1w_256x32_genblk1[1].ram_1rw_Rdata[0] [31]),
	.SCE(\ram_2r1w_256x32_genblk1[0].ram_1rw_web_reg ), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2172__1666 (
	.A0(io_in[25]),
	.A1(la_data_in[17]),
	.S(n_4),
	.X(addr[14]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2173__7410 (
	.A0(io_in[17]),
	.A1(la_data_in[9]),
	.S(n_4),
	.X(addr[6]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2174__6417 (
	.A0(io_in[11]),
	.A1(la_data_in[3]),
	.S(n_4),
	.X(addr[0]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2175__5477 (
	.A0(io_in[26]),
	.A1(la_data_in[18]),
	.S(n_4),
	.X(addr[15]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2176__2398 (
	.A0(io_in[18]),
	.A1(la_data_in[10]),
	.S(n_4),
	.X(addr[7]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2177__5107 (
	.A0(io_in[16]),
	.A1(la_data_in[8]),
	.S(n_4),
	.X(addr[5]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2178__6260 (
	.A0(io_in[24]),
	.A1(la_data_in[16]),
	.S(n_4),
	.X(addr[13]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2179__4319 (
	.A0(io_in[23]),
	.A1(la_data_in[15]),
	.S(n_4),
	.X(addr[12]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2180__8428 (
	.A0(io_in[20]),
	.A1(la_data_in[12]),
	.S(n_4),
	.X(addr[9]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2181__5526 (
	.A0(io_in[22]),
	.A1(la_data_in[14]),
	.S(n_4),
	.X(addr[11]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2182__6783 (
	.A0(io_in[14]),
	.A1(la_data_in[6]),
	.S(n_4),
	.X(addr[3]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2183__3680 (
	.A0(io_in[21]),
	.A1(la_data_in[13]),
	.S(n_4),
	.X(addr[10]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2184__1617 (
	.A0(io_in[15]),
	.A1(la_data_in[7]),
	.S(n_4),
	.X(addr[4]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2185__2802 (
	.A0(io_in[19]),
	.A1(la_data_in[11]),
	.S(n_4),
	.X(addr[8]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2186__1705 (
	.A0(io_in[13]),
	.A1(la_data_in[5]),
	.S(n_4),
	.X(addr[2]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__mux2_2 g2187__5122 (
	.A0(io_in[12]),
	.A1(la_data_in[4]),
	.S(n_4),
	.X(addr[1]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__or4bb_1 g2188__8246 (
	.A(n_1),
	.B(n_3),
	.C_N(la_oenb[16]),
	.D_N(la_oenb[11]),
	.X(n_4), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__or4bb_1 g2189__7098 (
	.A(n_2),
	.B(n_0),
	.C_N(la_oenb[7]),
	.D_N(la_oenb[8]),
	.X(n_3), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nand4_1 g2190__6131 (
	.A(la_oenb[10]),
	.B(la_oenb[9]),
	.C(la_oenb[5]),
	.D(la_oenb[6]),
	.Y(n_2), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nand4_1 g2191__1881 (
	.A(la_oenb[15]),
	.B(la_oenb[14]),
	.C(la_oenb[12]),
	.D(la_oenb[13]),
	.Y(n_1), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nand4_1 g2192__5115 (
	.A(la_oenb[18]),
	.B(la_oenb[17]),
	.C(la_oenb[3]),
	.D(la_oenb[4]),
	.Y(n_0), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and3b_1 g2__7482 (
	.A_N(n_18),
	.B(io_in[35]),
	.C(n_11),
	.X(io_out[29]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and3b_1 g3141__4733 (
	.A_N(n_16),
	.B(io_in[35]),
	.C(n_11),
	.X(io_out[30]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and3b_1 g3142__6161 (
	.A_N(n_14),
	.B(io_in[35]),
	.C(n_11),
	.X(io_out[27]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__and3b_1 g3143__9315 (
	.A_N(n_12),
	.B(io_in[35]),
	.C(n_11),
	.X(io_out[28]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2b_1 g3144__9945 (
	.A(n_9),
	.B_N(n_233),
	.Y(n_232), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__nor2b_1 g3145__2883 (
	.A(csb1),
	.B_N(n_283),
	.Y(n_233), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__inv_2 drc_bufs3194 (
	.A(n_284),
	.Y(n_283), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__inv_1 drc_bufs3195 (
	.A(csb0),
	.Y(n_284), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3205 (
	.A(addr[10]),
	.X(n_294), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3211 (
	.A(addr[8]),
	.X(n_300), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3217 (
	.A(addr[14]),
	.X(n_306), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3223 (
	.A(addr[12]),
	.X(n_312), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3229 (
	.A(addr[13]),
	.X(n_318), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3235 (
	.A(addr[9]),
	.X(n_324), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3241 (
	.A(addr[15]),
	.X(n_330), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3247 (
	.A(addr[11]),
	.X(n_336), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__inv_2 drc_bufs3251 (
	.A(n_341),
	.Y(n_340), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__inv_1 drc_bufs3252 (
	.A(web),
	.Y(n_341), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc (
	.A(n_318),
	.X(n_492), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3406 (
	.A(n_300),
	.X(n_496), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3410 (
	.A(n_330),
	.X(n_500), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3414 (
	.A(n_324),
	.X(n_504), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3418 (
	.A(n_312),
	.X(n_508), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3422 (
	.A(n_336),
	.X(n_512), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3426 (
	.A(n_306),
	.X(n_516), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3430 (
	.A(n_294),
	.X(n_520), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3431 (
	.A(addr[15]),
	.X(n_521), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3434 (
	.A(addr[9]),
	.X(n_524), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3437 (
	.A(addr[11]),
	.X(n_527), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3440 (
	.A(addr[13]),
	.X(n_530), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3443 (
	.A(addr[12]),
	.X(n_533), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3446 (
	.A(addr[8]),
	.X(n_536), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3449 (
	.A(addr[10]),
	.X(n_539), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3452 (
	.A(addr[14]),
	.X(n_542), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3458 (
	.A(addr[0]),
	.X(n_548), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3466 (
	.A(addr[7]),
	.X(n_556), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3474 (
	.A(addr[6]),
	.X(n_564), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3482 (
	.A(addr[0]),
	.X(n_572), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3490 (
	.A(addr[1]),
	.X(n_580), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3498 (
	.A(addr[4]),
	.X(n_588), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3506 (
	.A(addr[3]),
	.X(n_596), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3514 (
	.A(addr[4]),
	.X(n_604), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3522 (
	.A(addr[2]),
	.X(n_612), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3530 (
	.A(addr[1]),
	.X(n_620), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3538 (
	.A(addr[3]),
	.X(n_628), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3546 (
	.A(addr[2]),
	.X(n_636), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3554 (
	.A(addr[5]),
	.X(n_644), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3562 (
	.A(addr[7]),
	.X(n_652), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3570 (
	.A(addr[5]),
	.X(n_660), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3578 (
	.A(addr[6]),
	.X(n_668), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3583 (
	.A(addr[5]),
	.X(n_673), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3586 (
	.A(addr[7]),
	.X(n_676), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3589 (
	.A(addr[1]),
	.X(n_679), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3592 (
	.A(addr[0]),
	.X(n_682), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3595 (
	.A(addr[0]),
	.X(n_685), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3598 (
	.A(addr[7]),
	.X(n_688), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3601 (
	.A(addr[4]),
	.X(n_691), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3604 (
	.A(addr[4]),
	.X(n_694), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3607 (
	.A(addr[2]),
	.X(n_697), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3610 (
	.A(addr[5]),
	.X(n_700), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3613 (
	.A(addr[1]),
	.X(n_703), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3616 (
	.A(addr[3]),
	.X(n_706), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3619 (
	.A(addr[3]),
	.X(n_709), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3622 (
	.A(addr[6]),
	.X(n_712), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3625 (
	.A(addr[2]),
	.X(n_715), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_4 drc_bufs3628 (
	.A(addr[6]),
	.X(n_718), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3658 (
	.A(n_521),
	.X(n_748), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3662 (
	.A(n_718),
	.X(n_752), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3666 (
	.A(n_715),
	.X(n_756), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3670 (
	.A(n_712),
	.X(n_760), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3674 (
	.A(n_709),
	.X(n_764), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3678 (
	.A(n_706),
	.X(n_768), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3682 (
	.A(n_703),
	.X(n_772), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3686 (
	.A(n_700),
	.X(n_776), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3690 (
	.A(n_697),
	.X(n_780), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3694 (
	.A(n_694),
	.X(n_784), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3698 (
	.A(n_691),
	.X(n_788), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3702 (
	.A(n_688),
	.X(n_792), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3706 (
	.A(n_685),
	.X(n_796), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3710 (
	.A(n_682),
	.X(n_800), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3714 (
	.A(n_679),
	.X(n_804), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3718 (
	.A(n_676),
	.X(n_808), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3722 (
	.A(n_673),
	.X(n_812), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3726 (
	.A(n_668),
	.X(n_816), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3730 (
	.A(n_660),
	.X(n_820), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3734 (
	.A(n_652),
	.X(n_824), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3738 (
	.A(n_644),
	.X(n_828), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3742 (
	.A(n_636),
	.X(n_832), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3746 (
	.A(n_628),
	.X(n_836), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3750 (
	.A(n_620),
	.X(n_840), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3754 (
	.A(n_612),
	.X(n_844), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3758 (
	.A(n_604),
	.X(n_848), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3762 (
	.A(n_596),
	.X(n_852), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3766 (
	.A(n_588),
	.X(n_856), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3770 (
	.A(n_580),
	.X(n_860), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3774 (
	.A(n_572),
	.X(n_864), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3778 (
	.A(n_564),
	.X(n_868), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3782 (
	.A(n_556),
	.X(n_872), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3786 (
	.A(n_548),
	.X(n_876), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3790 (
	.A(n_542),
	.X(n_880), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3794 (
	.A(n_539),
	.X(n_884), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3798 (
	.A(n_536),
	.X(n_888), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3802 (
	.A(n_533),
	.X(n_892), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3806 (
	.A(n_530),
	.X(n_896), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3810 (
	.A(n_527),
	.X(n_900), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__buf_12 drc3814 (
	.A(n_524),
	.X(n_904), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
   sky130_fd_sc_hd__conb_1 tie_0_cell (
	.HI(io_oeb[0]),
	.LO(io_oeb[27]), 
	.VPWR(VPWR), 
	.VPB(VPWR), 
	.VNB(VGND), 
	.VGND(VGND));
endmodule

